## Numpy и линейная алгебра

In [7]:
import numpy as np

***Перемножение матриц***

In [20]:
def no_numpy_mult(first, second: list):
    res = [[0] * len(second[0]) for i in range(len(first))]
    for row_index in range(len(first)):
        for col_index in range(len(second[0])):
            col_to_mul = [i[col_index] for i in second]
            res[row_index][col_index] = sum(list(map(lambda x, y: x * y,
                                     first[row_index], col_to_mul)))
    return res
    
    
def numpy_mult(first, second):
    return np.dot(first, second)


no_numpy_mult([[1, 4], [2, 3]], [[5, 6], [0, 5]])

[[5, 26], [10, 27]]

***Скалярное произведение векторов в трехмерном пространстве***

In [24]:
def no_numpy_scalar(v1, v2):
    return sum(list(map(lambda x, y: x * y, v1, v2)))
    

def numpy_scalar (v1, v2):
    return np.dot(v1, v2)
    

a = [1, 3, 0]
b = [10, 5, 5]
print(numpy_scalar(a, b))
print(no_numpy_scalar(a, b))

25
25


***Сумма четных элементов на главной диагонали квадратной матрицы***

In [32]:
def diag_2k(a):
    return np.sum(a.diagonal()[a.diagonal() % 2 == 0])
    
    # OR
    # return np.sum([x for x in a.diagonal() if x % 2 == 0])

a = np.array([[2, 3], [1, 4]])
print(diag_2k(a))

6


***Двумерный массив из двумерного массива***

In [42]:
def cumsum(A):
    return np.cumsum(A, axis=1)

    # OR
    #return np.array([np.cumsum(row, axis=0) for row in A])

    
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a, end='\n\n')
print(cumsum(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


***Склеивание***

In [95]:
def transform(X, a=1):
    Y = np.copy(X)    
    Y[:, 1::2] = a
    Y[:, ::2] = Y[:, ::2] ** 3
    Y = Y[:, ::-1]
    return np.append(X, Y, axis=1)
    
x = np.array([[100, 200, 300, 400, 500]])
transform(x)

array([[      100,       200,       300,       400,       500, 125000000,
                1,  27000000,         1,   1000000]])

***Run-length encoding***

In [136]:
def encode(a):
    nums = np.array([], dtype="int32") 
    count = np.array([], dtype="int32")
    start = 0
    while start < len(a) - 1:
        end = start + 1
        while end < len(a) and a[end - 1] == a[end]:
            end += 1
        tmp = a[start:end]
        nums = np.append(nums, tmp[0])
        count = np.append(count, len(tmp))
        start = end
    return (nums, count)
        
        
encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3]))

(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))